# app/models/schemas.py
# Pydantic models for request and response schemas.

from pydantic import BaseModel, Field


# Request model for the /analyze endpoint, containing the raw transcript text.
class TranscriptRequest(BaseModel):
    transcript: str = Field(..., description="Raw meeting or lecture transcript text.")


# Response model for individual action items in the tactical checklist stream.
class ActionItem(BaseModel):
    who: str = Field(..., description="Speaker or assignee responsible for the task.")
    what: str = Field(..., description="Description of the task or commitment.")
    when: str | None = Field(None, description="Deadline or urgency indicator, if stated.")


# The combined response model for the dual-stream output, containing both the narrative summary and the list of action items.
class DualStreamResponse(BaseModel):
    narrative_notes: str = Field(
        ...,
        description="Stream 1 — concise narrative summary of themes and key discussion points.",
    )
    action_items: list[ActionItem] = Field(
        ...,
        description="Stream 2 — structured tactical checklist of Who / What / When commitments.",
    )


# Response model for the /transcribe endpoint, containing the raw transcript text generated by the Whisper API.
class TranscribeResponse(BaseModel):
    transcript: str = Field(..., description="Whisper-generated transcript text.")
